name = "USTB"
uuid = "f407a446-6911-41e8-a487-48c8a67903f1"
authors = ["Simon Andreas Bj√∏rn"]
version = "0.1.0"

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ContentHashes = "ac509c8a-358f-4e3e-a88a-d19fed7814aa"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UFF = "0d0b83d6-456a-42e3-bf29-fb85441d02cf"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
USTBMakieExt = ["GLMakie"]

[compat]
ContentHashes = "0.1"
CoordinateTransformations = "0.6"
GLMakie = "0.8.5"
StaticArrays = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
